### ISSUE TITLE
drop-shadow with spread argument throw an exception

### ISSUE THREAD

**Issue by MoOx** [iamvdo/pleeease-filters#6]
```css
a {
  filter: drop-shadow(10px 10px 10px 10px #000)
}
```
This just throw an exception.
I will try to fix and send a pr
